export const SET_IS_FETCHING = 'SET_IS_FETCHING'

export const SET_PEOPLE_DATA = 'SET_PEOPLE_DATA'
export const SET_CURRENT_PEOPLE_DATA = 'SET_CURRENT_PEOPLE_DATA'
export const SET_SERCHED_PEOPLE = 'SET_SERCHED_PEOPLE'
export const SET_PEOPLE_PAGE = 'SET_PEOPLE_PAGE'

export const SET_SPECIES_DATA = 'SET_SPECIES_DATA'
export const SET_CURRENT_SPECIES_DATA = 'SET_CURRENT_SPECIES_DATA'
export const SET_SERCHED_SPECIES = 'SET_SERCHED_SPECIES'
export const SET_SPECIES_PAGE = 'SET_SPECIES_PAGE'

export const SET_VEHICLES_DATA = 'SET_VEHICLES_DATA'
export const SET_CURRENT_VEHICLES_DATA = 'SET_CURRENT_VEHICLES_DATA'
export const SET_SERCHED_VEHICLES = 'SET_SERCHED_VEHICLES'
export const SET_VEHICLES_PAGE = 'SET_VEHICLES_PAGE'

export const SET_STARSHIPS_DATA = 'SET_STARSHIPS_DATA'
export const SET_CURRENT_STARSHIPS_DATA = 'SET_CURRENT_STARSHIPS_DATA'
export const SET_SERCHED_STARSHIPS = 'SET_SERCHED_STARSHIPS'
export const SET_STARSHIPS_PAGE = 'SET_STARSHIPS_PAGE'

export const SET_PLANETS_DATA = 'SET_PLANETS_DATA'
export const SET_CURRENT_PLANETS_DATA = 'SET_CURRENT_PLANETS_DATA'
export const SET_SERCHED_PLANETS = 'SET_SERCHED_PLANETS'
export const SET_PLANETS_PAGE = 'SET_PLANETS_PAGE'

export const SET_FILMS_DATA = 'SET_FILMS_DATA'
export const SET_CURRENT_FILMS_DATA = 'SET_CURRENT_FILMS_DATA'
export const SET_SERCHED_FILMS = 'SET_SERCHED_FILMS'
export const SET_FILMS_PAGE = 'SET_FILMS_PAGE'

export const SET_THUMBNAILS_FILMS = 'SET_THUMBNAILS_FILMS'
export const SET_THUMBNAILS_HOMEWORLD = 'SET_THUMBNAILS_HOMEWORLD'
export const SET_THUMBNAILS_STARSHIPS = 'SET_THUMBNAILS_STARSHIPS'
export const SET_THUMBNAILS_VEHICLES = 'SET_THUMBNAILS_VEHICLES'
export const SET_THUMBNAILS_SPECIES = 'SET_THUMBNAILS_SPECIES'
export const RESET_THUMBNAILS_STORE = 'RESET_THUMBNAILS_STORE'
