export const SET_IS_FETCHING = 'SET_IS_FETCHING'

export const SET_PEOPLE_DATA = 'SET_PEOPLE_DATA'
export const SET_CURRENT_PEOPLE_DATA = 'SET_CURRENT_PEOPLE_DATA'
export const SET_SERCHED_PEOPLE = 'SET_SERCHED_PEOPLE'
export const SET_PEOPLE_PAGE = 'SET_PEOPLE_PAGE'

export const SET_SPECIES_DATA = 'SET_SPECIES_DATA'
export const SET_CURRENT_SPECIES_DATA = 'SET_CURRENT_SPECIES_DATA'
export const SET_SERCHED_SPECIES = 'SET_SERCHED_SPECIES'
export const SET_SPECIES_PAGE = 'SET_SPECIES_PAGE'
